upstream:
  externalResolvers:
    - udp:1.1.1.1
    - udp:1.0.0.1
blocking:
  blackLists:
    ads:
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://mirror1.malwaredomains.com/files/justdomains
      - http://sysctl.org/cameleon/hosts
      - https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
  clientGroupsBlock:
    default:
      - ads
  blockType: zeroIp
# clientLookup:
#   upstream: udp:10.8.55.1
#   singleNameOrder:
#       - 2
#       - 1
#   clients:
#     nuc:
#       - 10.8.55.40
queryLog:
    dir: /logs
    perClient: true
    logRetentionDays: 30
prometheus:
  enable: true
port: 53
httpPort: 4000